In [1]:
from statsmodels.tsa.arima.model import ARIMA
from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
import math

In [2]:

df =read_csv('rainfallPred.csv')
df.head()

,Days,January,February,March,April,May,June,July,August,September,October,November,December
0,1,11,0,0,0,0,0,1,1,0,0,0,0
1,2,12,0,0,0,0,0,0,1,0,1,0,0
2,3,9,0,0,0,1,0,0,0,0,0,0,0
3,4,6,0,0,0,0,1,0,0,0,0,0,0
4,5,41,0,1,0,0,0,0,1,0,0,0,0

In [4]:
from statsmodels.tsa.arima.model import ARIMA

# Assume 'df' contains the dataset with columns for each month's rainfall (0 or 1)

# Select the month for forecasting (change 'January' to your desired month)
selected_month = 'January'

# Extract the selected month's data
month_data = df[selected_month]

# Use ARIMA model for forecasting for the selected month
model_month = ARIMA(month_data, order=(1, 0, 0))  # Adjust the order as needed
model_fit_month = model_month.fit()  # Fit the model to the data
forecast_month = model_fit_month.forecast(steps=len(month_data))  # Forecast for the selected month

# Display the day-wise forecast for the selected month
print(f"Day-wise Forecast for '{selected_month}':")
for day, prediction in enumerate(forecast_month, start=1):
    print(f"Day {day} = {prediction}")

# Use ARIMA model for forecasting for January in the next year
# Assuming the dataset represents one year (adjust accordingly)
rainfall_data_next_year = df['January'].values  # Replace 'January' with the column representing January

model_next_year = ARIMA(rainfall_data_next_year, order=(1, 0, 0))  # Adjust the order as needed
model_fit_next_year = model_next_year.fit()  # Fit the model to the data
forecast_jan_next_year = model_fit_next_year.forecast(steps=20)  # Forecast for January next year

# Display the forecast for January next year
print("\nForecasted rainfall for January next year:")
print(forecast_jan_next_year)

Day-wise Forecast for 'January':
Day 1 = 15.296558065402138
Day 2 = 17.482880055784978
Day 3 = 18.93287843312237
Day 4 = 19.89453701018901
Day 5 = 20.532322012779154
Day 6 = 20.955309671007804
Day 7 = 21.235840819101814
Day 8 = 21.42189287882504
Day 9 = 21.545285126575205
Day 10 = 21.62712053773641
Day 11 = 21.681394891612207
Day 12 = 21.717390378734926
Day 13 = 21.74126307367602
Day 14 = 21.757095768530448
Day 15 = 21.767596226353575
Day 16 = 21.774560272304637
Day 17 = 21.779178921969763
Day 18 = 21.782242073028655
Day 19 = 21.784273596328735
Day 20 = 21.785620930116526
Day 21 = 21.786514500146293
Day 22 = 21.787107127901447
Day 23 = 21.787500166661115
Day 24 = 21.78776083529376
Day 25 = 21.787933714264017
Day 26 = 21.78804836994029
Day 27 = 21.78812441113883
Day 28 = 21.788174842692364
Day 29 = 21.78820828958221
Day 30 = 21.7882304720129
Day 31 = 21.788245183701587

Forecasted rainfall for January next year:
[15.29655807 17.48288006 18.93287843 19.89453701 20.53232201 20.95530967
 21.23584082 21.42189288 21.54528513 21.62712054 21.68139489 21.71739038
 21.74126307 21.75709577 21.76759623 21.77456027 21.77917892 21.78224207
 21.7842736  21.78562093]